services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SQLD_NODE: primary
    volumes:
      - libsql-data:/var/lib/sqld

volumes:
  libsql-data: